# ####################################################################

#  Created by Genus(TM) Synthesis Solution GENUS15.23 - 15.20-s040_1 on Wed Aug 10 21:58:10 +0530 2016

# ####################################################################

set sdc_version 1.7

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design sixtyfour_bit_adder

create_clock -name "clk" -period 1.65 -waveform {0.0 0.825} 
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports C]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {B[63]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[32]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[33]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[34]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[35]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[36]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[37]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[38]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[39]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[40]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[41]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[42]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[43]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[44]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[45]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[46]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[47]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[48]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[49]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[50]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[51]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[52]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[53]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[54]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[55]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[56]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[57]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[58]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[59]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[60]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[61]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[62]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {A[63]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports carry]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[32]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[33]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[34]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[35]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[36]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[37]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[38]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[39]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[40]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[41]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[42]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[43]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[44]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[45]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[46]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[47]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[48]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[49]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[50]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[51]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[52]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[53]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[54]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[55]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[56]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[57]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[58]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[59]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[60]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[61]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[62]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.15 [get_ports {sum[63]}]
set_wire_load_mode "segmented"
set_wire_load_selection_group "WireAreaForZero" -library "tcbn45gsbwpbc0d88_ccs"
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/BHDBWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/BUFFD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/BUFFD24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/BUFTD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/BUFTD24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKBD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKBD24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKLHQD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKLHQD24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKLNQD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKLNQD24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKND20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/CKND24BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/DCCKBD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/DCCKND20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GAN2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GAN2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GAOI21D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GAOI21D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GAOI22D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GBUFFD1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GBUFFD2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GBUFFD3BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GBUFFD4BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GBUFFD8BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDCAP10BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDCAP2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDCAP3BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDCAP4BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDCAPBWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDFCNQD1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GDFQD1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GFILL10BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GFILL2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GFILL3BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GFILL4BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GFILLBWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GINVD1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GINVD2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GINVD3BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GINVD4BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GINVD8BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GMUX2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GMUX2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GMUX2ND1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GMUX2ND2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND2D3BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND2D4BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND3D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GND3D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GNR2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GNR2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GNR3D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GNR3D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GOAI21D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GOAI21D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GOR2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GOR2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GSDFCNQD1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GTIEHBWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GTIELBWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GXNR2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GXNR2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GXOR2D1BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/GXOR2D2BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/INVD20BWP]
set_dont_use [get_lib_cells tcbn45gsbwpbc0d88_ccs/INVD24BWP]
